name: Deploy to Ubuntu Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH
      run: sudo apt-get install openssh-client

    - name: Add SSH known hosts
      run: ssh-keyscan -H 192.227.134.27 >> ~/.ssh/known_hosts

    - name: Deploy code
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: root@192.227.134.27
        REMOTE_PATH: /path/to/code
      run: |
        mkdir -p ~/.ssh && \
        echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa && \
        chmod 600 ~/.ssh/id_rsa && \
        scp -r -o StrictHostKeyChecking=no ./ $REMOTE_HOST:$REMOTE_PATH
