on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y nodejs npm
        cd /root/main
        npm install

    - name: Build
      run: |
        sudo -s cd /root/main
        npm run build

    - name: Deploy
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_HOST: 192.227.134.27
        SSH_USERNAME: root
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      with:
        source: /root/main/build
        server_path: /var/www/myapp
