name: Deploy to Ubuntu Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install SSH
      run: sudo apt-get install openssh-client
    - name: Add SSH known hosts
      run: ssh-keyscan -H 192.227.134.27 >> ~/.ssh/known_hosts
    - name: Deploy code
      run: ssh root@192.227.134.27 "cd /path/to/code && git pull"
      env:
  PASS: "${{ ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDU2uRG26m5ONifZl8VRxBBzuGefIWrRkJFyKkbudW4mTStrsFY55141sGFxE3BuH91dYfXqyBfe0460OLEVyKD/05qK4Bqou3wgbSs6+IuGkWwfzjWRd0G4z+kT+Y6zHyj7qeFkY4YQ11de8RDssdm1WJepI56kk0ir/g3u5Yxv/J9ul+pxOYMobw8vOHEiMx2bBxZ2H63JG3DyVr9uYC2u3mD2U2XJvH9LSWubJv6NjUuOQjZyC2/ip/oiGQxNcsH+Pwl0K0Dy4HaqOxbMavtq4mTseOVYRIhtBUEvxuN/6fMCjYqzxieMzHG9bwNUXMZnczWEnEWhbwMgeZ5ETBxGSHVNHCMKmw/b6Dz+tibNKwZ2xA7eOroEkQzIi3miEPFXs0ZmPFBV4PZO4ACL/pIinYT6DVRBW/NIlatDNdBPZRulFnat/EX1chXI9aBQOQzzsPZbQL+DLefptikp/bG+Wv6FF8zINGcDv8bCDhW5LMbDs3V6z8kFZPFpwtpaoe87JCBK3Sk7efiRADc5Iw2sNF3FeJX+9qgxaeVZLl1r830xqF55MO7GlkG8AXce5g6vBogqCinY9qXWkzmI5wA4++wwmW8oOQozu7hUivImfLNsw08d9x6SMqILjTxGebKipQI6FvzStOc3ufM2YqQScWSQOCOc9FkX9l2Rpp7ZQ== root@amghezi
 }}"
