name: Deploy to Ubuntu Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      REMOTE_HOST: root@192.227.134.27
      REMOTE_PATH: /path/to/code

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH
        run: sudo apt-get install openssh-client

      - name: Add SSH known hosts
        run: ssh-keyscan -H 192.227.134.27 >> ~/.ssh/known_hosts

      - name: Deploy code
        run: |
          echo "${SSH_PRIVATE_KEY}" > ssh_key
          chmod 600 ssh_key
          scp -i ssh_key -r ./* $REMOTE_HOST:$REMOTE_PATH
          ssh -i ssh_key $REMOTE_HOST "cd $REMOTE_PATH && git pull"
