name: Deploy to Ubuntu Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install SSH
      run: sudo apt-get install openssh-client
    - name: Add SSH known hosts
      run: ssh-keyscan -H 192.227.134.27 >> ~/.ssh/known_hosts
    - name: Deploy code
      run: ssh root@192.227.134.27 "cd /path/to/code && git pull"
      env:
        PASS: ${{ 4rK85S3WYvBlwZ0hd4 }}
