name: Deploy to Server
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: 192.227.134.27
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/html
            rm -rf *
            scp -r ${{ github.workspace }}/dist/* ./
            systemctl reload nginx
